### PR TITLE
Fix hdbsite

### LINKED ISSUE #668: HDB siteDAO sitecode string init skipped
HDBSiteDAO only queries sitecode if it's null, and it has a default which only works for one office.

Fix underway.

### PR DESCRIPTION
**Pull request by agilmore2**
## Problem Description

Fixes #668 

## Solution

Added a boolean fence to synchronized string. Please review for best practice.

## how you tested the change

Observed that sitecode is queried now, when before it was not.

## Where the following done:

- [X] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [X] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

### CODE REVIEW

File: src/main/java/decodes/hdb/HdbSiteDAO.java [hunk 1]
```diff
@@ -102,7 +103,7 @@ public HdbSiteDAO(DatabaseConnectionOwner tsdb)
 			}
 		}
 		
-		if (myDbSiteCode == null)
+		if (!siteCodeInit)
```
Comment (MikeNeilson) [inline src/main/java/decodes/hdb/HdbSiteDAO.java:106]: AtomicBoolean *might* be better here, but given the synchronized block it's probably fine like this.

Though I'd move the synchronized to either siteCodeInit or at least before siteCodeInit; there's a small chance of a race condition or sequencing issue *if* this gets called again.

**Review by MikeNeilson — APPROVED** [review]

File: src/main/java/decodes/hdb/HdbSiteDAO.java (hunk 1 above)
Comment (agilmore2) [reply src/main/java/decodes/hdb/HdbSiteDAO.java:106]: If you're good as is, I'll merge. I would like to know more about how a race condition could be an issue here. Perhaps a deep discussion for September.

Comment (MikeNeilson) [reply src/main/java/decodes/hdb/HdbSiteDAO.java:106]: Hard to say really, it's just that your checking the state of a variable and then synchronizing on a different object after which you set the value of the first. So not really a race condition but if two threads were calling that the both would check and start, though presumably it would get stopped at the synchronization block so maybe not an issue right now.
