### PR TITLE
fix and test for issue #964  (importing network list)

### LINKED ISSUE #964: DBIMPORT a netlist
While importing netlists from dbexport XML databases to Postgres for several districts some of them will successfully overwrite the netlist but others don't.  I'm using dbimport against the netlist XML file written to the netlist folder after importing the whole XML database to disk. Below is an example of both scenarios.  The netlist XML's both look ok but MVR and several others will not overwrite what's in the database.  It looks like dbimport skips the overwrite step in some cases. There are no platform definitions in this step, just netlists to process, so it stating there are no platforms to import is accurate.  All the netlist XML's are populated/non-empty and have what appears to be consistent formatting from the dbexport that created them.  I included snippets of the XML and the log file entry for SAJ (works) and MVR (does not work).  Git Hub would not allow uploading the full XML file for each:

SAJ Netlist XML snippet:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<NetworkList Name="SAJ-RIVERGAGES-DAS">
  <TransportMediumType>goes</TransportMediumType>
  <SiteNameTypePreference>nwshb5</SiteNameTypePreference>
  <NetworkListEntry TransportId="CE23D25A">
    <PlatformName>S78</PlatformName>
    <Description></Description>
  </NetworkListEntry>
  <NetworkListEntry TransportId="DE484126">
    <PlatformName>G1183</PlatformName>
    <Description>G -1183</Description>
  </NetworkListEntry>
  <NetworkListEntry TransportId="CE6BC656">
    <PlatformName>S12C</PlatformName>
    <Description>
      TAMIAMI CANAL BELOW S-12-C, NEARMIAMI, FLA Changed 08272015 from
      SU8200D-USGSFL-163 to SU8200D-USGSFL-263 due to SU9210 issue AG
    </Description>
  </NetworkListEntry>

SAJ log entry:

DBG3    03/07/25 10:35:35 Initializing the staging database.
DBG1    03/07/25 10:35:35 Creating XmlDatabaseIO for directory ''
INFO    03/07/25 10:35:35 Copying existing enumerations into staging db.
INFO    03/07/25 10:35:35 Processing '/wm/da/opendcs/dbhub/SAJ/current/netlist/SAJ-RIVERGAGES-DAS.xml'
DBG3    03/07/25 10:35:35 After readXmlFiles, there are 0 platforms to import:
DBG3    03/07/25 10:35:35 mergeStageToTheDb 1: #EUs=160
DBG3    03/07/25 10:35:35 mergeStageToTheDb 3: #stageEUs=160
INFO    03/07/25 10:35:35 Overwriting NetworkList 'SAJ-RIVERGAGES-DAS'
DBG3    03/07/25 10:35:35 After mergeStageToTheDb, there are 160 EUs
DBG3    03/07/25 10:35:35 After normalizeTheDb, there are 160 EUs
DBG2    03/07/25 10:35:35 Writing modified EquipmentModels
DBG2    03/07/25 10:35:35 Writing modified configs
DBG1    03/07/25 10:35:35 Before writing sites...
DBG2    03/07/25 10:35:35 Writing modified Sites
DBG1    03/07/25 10:35:35 After writing sites...
DBG2    03/07/25 10:35:35 Writing modified Platforms
DBG2    03/07/25 10:35:35 Writing modified simple DataSources
DBG2    03/07/25 10:35:35 Writing modified group DataSources
DBG2    03/07/25 10:35:35 Writing modified RoutingSpecs
DBG2    03/07/25 10:35:35 Writing Processes.
DBG2    03/07/25 10:35:35 Writing other modified objects.
DBG3    03/07/25 10:35:35 Writing NetworkList

MVR Netlist XML snippet:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<NetworkList Name="MVR-RIVERGAGES-DAS">
  <TransportMediumType>goes</TransportMediumType>
  <SiteNameTypePreference>nwshb5</SiteNameTypePreference>
  <NetworkListEntry TransportId="DD31104C">
    <PlatformName>WDMI4</PlatformName>
    <Description>Raccoon River near West Des Moines, IA (USGS)</Description>
  </NetworkListEntry>
  <NetworkListEntry TransportId="CE45A8E4">
    <PlatformName>LUSM7</PlatformName>
    <Description>Mississippi River at Louisiana, MO (MVS)</Description>
  </NetworkListEntry>
  <NetworkListEntry TransportId="CE7D2C26">
    <PlatformName>LNRI2</PlatformName>
    <Description>Vermilion River near Leonore, IL (USGS)</Description>
  </NetworkListEntry>
  <NetworkListEntry TransportId="17361622">
    <PlatformName>PYMI3</PlatformName>
    <Description>Yellow River at Plymouth, IN (USGS)</Description>
  </NetworkListEntry>

MVR log entry:

DBG3    03/07/25 14:37:13 Initializing the staging database.
DBG1    03/07/25 14:37:13 Creating XmlDatabaseIO for directory ''
INFO    03/07/25 14:37:13 Copying existing enumerations into staging db.
INFO    03/07/25 14:37:13 Processing '/wm/da/opendcs/dbhub/MVR/current/netlist/MVR-RIVERGAGES-DAS.xml'
DBG3    03/07/25 14:37:13 After readXmlFiles, there are 0 platforms to import:
DBG3    03/07/25 14:37:13 mergeStageToTheDb 1: #EUs=160
DBG3    03/07/25 14:37:13 mergeStageToTheDb 3: #stageEUs=160
DBG3    03/07/25 14:37:13 After mergeStageToTheDb, there are 160 EUs
DBG3    03/07/25 14:37:13 After normalizeTheDb, there are 160 EUs

### PR DESCRIPTION
**Pull request by ktarbet**
## Problem Description

Fixes #964 

## Solution

Fix the NetworkList.equals(Object ob) method to consider the number of entries.

## how you tested the change

created a junit test to capture the bug and the bug fix.

### CODE REVIEW

File: java/opendcs/src/main/java/decodes/db/NetworkList.java [hunk 1]
```diff
@@ -214,6 +215,11 @@ public boolean equals(Object ob)
 		if (!siteNameTypePref.equalsIgnoreCase(nl.siteNameTypePref))
 			return false;
 
+		if (this.networkListEntries.size() != nl.networkListEntries.size())
```
Comment (MikeNeilson) [inline java/opendcs/src/main/java/decodes/db/NetworkList.java:218]: Looking at the code below. Is is possible for these to be the same size but have 

A is a subset of B
B is not a subset of A.

I'm pretty sure now, but Set Theory was never my strong suit.
