### PR TITLE
Fix vertically averaged density to use depth/thickness average rather than volumetric average.

### LINKED ISSUE #1025: Fix vertically averaged density computations in ResEvapAlgo
The vertically averaged density, within the vertical temperature profile computation, is computed as a volumetric average. Since the model is 1-dimensional, the vertical averages should not be volumetric. By computing as a volumetric average, the densities become inconsistent with the vertically integrated temperatures. The average density should replace the volume average with a depth average, which ensures consistency between model variables.

### PR DESCRIPTION
**Pull request by rma-kayla**
## Problem Description
The vertically averaged density, within the vertical temperature profile computation, is computed as a volumetric average. Since the model is 1-dimensional, the vertical averages should not be volumetric. 

Fixes #1025. 

## Solution

The average density should replace the volume average with a depth/thickness-weighted average.
Update calculations in the Reservoir water temperature compute 

## how you tested the change

Created unit tests to verify calculations are accurate 
Ran integration tests with existing expected outputs to prove failure after code changes.
Ran ResEvapComputes for Test1 and Test2 and updated expected outputs.
Ran passing integration tests

## Where the following done:

- [ ] Tests. Check all that apply:
   - [x] Unit tests created or modified that run during ant test.
   - [x] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [x] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

### CODE REVIEW

File: java/opendcs/src/test/java/decodes/cwms/resevapcalc/ResWaterTemperatureComputeTest.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+    {
+        for (int i = 0; i < RHOW_VALUES.length; i++)
+        {
+            RHOW_DEPTH_PRODUCTS[i] = RHOW_VALUES[i] * DEPTH_VALUES[i];
+            RHOW_VOLUME_PRODUCTS[i] = RHOW_VALUES[i] * VOLUME_VALUES[i];
+        }
+    }
+
+
+    @MethodSource("getLayerIndexValues")
```
Comment (MikeNeilson) [inline java/opendcs/src/test/java/decodes/cwms/resevapcalc/ResWaterTemperatureComputeTest.java]: The inputs to a parameterized test should be the individual values, not a single index to multiple arrays.

File: integrationtesting/opendcs-tests/src/test/resources/data/Comps/ResEvap/Test1/timeseries/expectedOutputs/ResEvapOutputs_ts.tsimport
Comment (MikeNeilson) [inline integrationtesting/opendcs-tests/src/test/resources/data/Comps/ResEvap/Test1/timeseries/expectedOutputs/ResEvapOutputs_ts.tsimport]: i can't meaningfully tell what was actually changed in this file  ( other than the line 1 to 3), please describe or more lightly adjust.

**Review by oskarhurst — APPROVED** [review]
Everything Looks good to me!
