### PR TITLE
Bugfix/1057 cwms location name size limit

### LINKED ISSUE #1057: Please Remove the 16 Character Limit
**Describe the bug**
CCP is still restricting the length of base location to 16 characters, as shown in the screenshots section. The 2016 CWMS Naming Convention says the max is 24 characters.

**To Reproduce**
1) Example 1: Create a computation with an output that has a base location longer than 16 characters, as shown in the first screenshot in the screenshots section. It will give an error.
2) Example 2: Create a computation using a group with TSID that has a base location longer than 16 characters. Running the computation and then using the trace feature shows that the computation fails due to the base location being longer than 16 characters. Please see second screenshot.

**Expected behavior**
Should allow up to 24 characters in base location.

**Screenshots**

Example 1:
Image

Example 2:
Image

**Desktop/ServerSide (please complete the following information):**
 - Desktop: Windows 11, client side OpenDCS 7.0.15-RC3
 - Server: CWMS 3.4.0, OpenDCS 7.0.15-RC3

**Additional context**

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Fixes #1057. 

## Solution

Remove Excessive validation that can vary based on database schema updates.

## how you tested the change

Added integration test to cover creation of the time series.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [x] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: integrationtesting/opendcs-tests/src/test/java/org/opendcs/fixtures/annotations/EnableIfTsDb.java [hunk 1]
```diff
@@ -47,21 +47,37 @@ public ConditionEvaluationResult evaluateExecutionCondition(ExtensionContext ctx
...
                     Optional<AnnotatedElement> element = ctx.getElement();
                     EnableIfTsDb anno = element.get().getAnnotation(EnableIfTsDb.class);
-                    if (anno.impl().isEmpty())
+                    final String configName = configs.get(0).getName();
+                    if (anno.value().length == 0)
                     {
                         retVal = ConditionEvaluationResult.enabled("Is Timeseries Db");
                     }
-                    else if (anno.impl().equalsIgnoreCase(configs.get(0).getName()))
+                    else if (matches(anno.value(),configName))
```
Comment (ktarbet) [inline integrationtesting/opendcs-tests/src/test/java/org/opendcs/fixtures/annotations/EnableIfTsDb.java:55]: Are you OK that this matches() is case sensitive; different from previous version of this file.

Comment (MikeNeilson) [reply integrationtesting/opendcs-tests/src/test/java/org/opendcs/fixtures/annotations/EnableIfTsDb.java:55]: Hmm, didn't even notice that, good question. But I feel like those probably should be identical to the actual provider name.

**Review by ktarbet — APPROVED** [review]
looks ok to me, I have one question in the code.
