### PR TITLE
Explore/rledit not working

### LINKED ISSUE #1110: rledit program won't start - java.lang.NullPointerException
**Describe the bug**
rledit (decodes.rledit.RefListEditor) is crashing on startup.

**To Reproduce**

 C:\project\opendcs\install\build\install\opendcs\bin>rledit
Exception in thread "main" java.lang.NullPointerException
        at decodes.rledit.EUTableModel.rebuild(EUTableModel.java:76)
        at decodes.rledit.EUTableModel.<init>(EUTableModel.java:67)
        at decodes.rledit.RefListFrame.<init>(RefListFrame.java:60)
        at decodes.rledit.RefListEditor.<init>(RefListEditor.java:31)
        at decodes.rledit.RefListEditor.main(RefListEditor.java:108)

**Expected behavior**
no crashing

### PR DESCRIPTION
**Pull request by ktarbet**
## Problem Description

Fixes #1110  rledit program is crashing

## Solution

restore functionality by connecting with legacy database using getLegacyDatabase(Database.class);

## how you tested the change

manually tested.

### CODE REVIEW

File: java/opendcs/src/main/java/decodes/rledit/EUTableModel.java [hunk 1]
```diff
@@ -52,11 +52,14 @@ public class EUTableModel extends AbstractTableModel
...
 	private int lastSortColumn;
 
+	Database db;
+
 	/**
 	 * No args constructor for JBuilder.
 	 */
 	public EUTableModel()
 	{
+		this.db = Database.getDb();
```
Comment (MikeNeilson) [inline java/opendcs/src/main/java/decodes/rledit/EUTableModel.java:62]: In the constructor would be better, but this is still a good improvement.

Also EngineeringUnitsList is a good candidate for migration to the new DAOs. While used just about everywhere it's contents are fairly constrained.

File: java/opendcs/src/main/java/decodes/rledit/RefListFrame.java [hunk 2]
```diff
@@ -104,18 +103,39 @@ public class RefListFrame extends JFrame
...
      * constructor for RefListFrame
      */
-    public RefListFrame(OpenDcsDatabase database)
+    public RefListFrame(OpenDcsDatabase database) throws DecodesException
     {
         this.database = database;
+        log.info("RefListFrame:initDecodes()");
+		Optional<Database> db = this.database.getLegacyDatabase(Database.class);
+		if (db.isPresent()) 
+        {
```
Comment (MikeNeilson) [inline java/opendcs/src/main/java/decodes/rledit/RefListFrame.java:120]: This should only be done in a main function. not in individual classes, even the GUI ones.

**Review by MikeNeilson — CHANGES_REQUESTED** [review]
Definitely an improvement.

The initializeForDecoding (though really should be ForEditing here) should happen in the RefListEditor main. 

No class that uses OpenDcsDatabase should need to know about initialization.

File: java/opendcs/src/main/java/decodes/rledit/EUTableModel.java (hunk 1 above)
Comment (MikeNeilson) [reply java/opendcs/src/main/java/decodes/rledit/EUTableModel.java:62]: you would have to create the DAO and change all the usages. i wasn't suggesting to do it for this PR.

**Review by MikeNeilson — APPROVED** [review]
