### PR TITLE
Bugfix/1019 cwms multi office

### LINKED ISSUE #1019: CWMS implementation does not correctly support multiple offices
**Describe the bug**
If data for multiple offices is used within the system a combination of the following will happen:
1. Data will only be saved as the default office configured at database install
2. Some tables do not include the office_code field and return results to queries when they shouldn't - some places in java handle this gracefully and some do not.
3. Subsubcription system only started for a single office at this time.

**To Reproduce**
Do things like dbimport with a profile with a different office.

**Expected behavior**
Data between offices stays independent

**Screenshots**

**Desktop/ServerSide (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Fixes #1019. 

Describe the problem you are trying to solve.

## Solution

Add trigger to set office ID based on current session.

May need to update some tables to include the office_code field.

## how you tested the change

Existing tests should not break. Additional tests that insert data for a different office are needed.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: java/opendcs/src/main/java/decodes/cwms/database/CwmsOracleProvider.java [hunk 1]
```diff
@@ -45,23 +45,23 @@ public class CwmsOracleProvider implements MigrationProvider
...
         properties.add(
             new MigrationProperty(
                 "DEFAULT_OFFICE", String.class,
-                ""));
+                "Ascii value of the default office to assign"));
         properties.add(
             new MigrationProperty(
                 "TABLE_SPACE_SPEC", String.class,
-                ""));
+                "If data will be on a separate table space indicate the line here."));
```
Comment (ktarbet) [inline java/opendcs/src/main/java/decodes/cwms/database/CwmsOracleProvider.java:64]:
```suggestion
                "Name of table space, leave blank if you don't need a separate table space"));
```

File: java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/beforeMigrate__set_schema_permissions.sql [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+GRANT CREATE ANY CONTEXT TO ${CCP_SCHEMA};
+GRANT SELECT ON dba_scheduler_jobs to ${CCP_SCHEMA};
+GRANT SELECT ON dba_queue_subscribers to ${CCP_SCHEMA};
+GRANT SELECT ON dba_subscr_registrations to ${CCP_SCHEMA};
+GRANT SELECT ON dba_queues to ${CCP_SCHEMA};
+GRANT EXECUTE ON dbms_aq TO ${CCP_SCHEMA};
+GRANT EXECUTE ON dbms_aqadm TO ${CCP_SCHEMA};
+GRANT EXECUTE ON DBMS_SESSION to ${CCP_SCHEMA};
+GRANT EXECUTE ON DBMS_RLS to ${CCP_SCHEMA};
```
Comment (ktarbet) [inline java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/beforeMigrate__set_schema_permissions.sql:31]: Other parts of the code have  suffix '_users'    , but why not on these grants?

I see one example below where both with and without the '_users' is used.

${CWMS_SCHEMA}.cwms_env

File: java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/afterMigrate__activateOfficeTrigger.sql [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+
+  for rec in (
+    select table_name from user_tab_columns where column_name in ('DB_OFFICE_CODE')
+    )
+  loop
+    execute immediate 'alter table ' || rec.table_name || ' modify db_office_code default null';
+    the_sql := 
+    'create or replace trigger ' || rec.table_name || '_get_office' ||
+    ' before insert or update on ' || rec.table_name ||
+    ' for each row begin set_office_column(:new.db_office_code,:old.db_office_code); end;';
```
Comment (ktarbet) [inline java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/afterMigrate__activateOfficeTrigger.sql:13]: Will that work --  passing :new.db_office_code  by 'reference'  into set_office_column?  The :new.db_office_code feels like it is a value type.

**Review by ktarbet — COMMENTED** [review]
Mostly some questions,  and one language change that didn't seem to copy from another PR.

File: java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/beforeMigrate__set_schema_permissions.sql (hunk 2 above)
Comment (MikeNeilson) [reply java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/beforeMigrate__set_schema_permissions.sql:31]: These grants are specific to the CCP schema "user". Their uses is through the CCP procedures which handle additional permissions checks.

the ${CCP_SCHEMA}_users is the name of the role granted to anyone who has an account and will use CCP.

File: java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/afterMigrate__activateOfficeTrigger.sql (hunk 3 above)
Comment (MikeNeilson) [reply java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/afterMigrate__activateOfficeTrigger.sql:13]: `:new` and `:old` are triggerisms. They are provided by the engine that executes the trigger.

one or the other may be null, otherwise they will match the datatype of the insert itself. the set_office_column method then handles the various conditions; which due to how the triggers work I was not able to handle in the trigger directly. (There can be a lot of quirks in triggers.)

**Review by ktarbet — APPROVED** [review]
