### PR TITLE
Bugfix/routing2

### LINKED ISSUE #117: CWMS Connection Pool mechanism leaking connections during RouteScheduler
**Describe the bug**
Eventually the system exits because no connections are available.

**To Reproduce**
1. setup system (making sure tracing is turned on)
2. run routsched
3. watch logs
4. see after freeConnection see number increase

**Expected behavior**
connections close system is stable.

**Desktop/ServerSide (please complete the following information):**
 - OS: Ubuntu 22.04/Java 11
 - Version: master branch latest

Continuing to investigate.

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Fixes #117. 

## Solution

Reduce duplication in logic and allow better tracking to ensure connections are regularly returned to the pool for recycling.

## how you tested the change

Running programs with Oracle connect_time set to 5 minutes. routsched, compproc, compdepends, gui apps.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests that run during ant test
   - [ ] Test procedure descriptions
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

**Comment by MikeNeilson** [comment]
This is draft number 2, still working out some kinks but the initial changes will make it easier to track down the problem I'm having.

File: src/main/java/decodes/cwms/CwmsConnectionPool.java [hunk 1]
```diff
@@ -0,0 +1,399 @@
...
+        return ret;
+    }
+
+    /**
+	 * Converts a CWMS String Office ID to the numeric office Code.
+	 * @param con the Connection
+	 * @param officeId the String office ID
+	 * @return the office code as a DbKey or Constants.undefinedId if no match.
+	 */
+	private DbKey officeId2code(Connection con, String officeId) throws SQLException
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsConnectionPool.java:312]: Small efficiency here: we could cache the mapping of officeId -> code since I doubt the codes would ever change throughout the lifetime of the application.

File: src/main/java/decodes/cwms/CwmsConnectionPool.java [hunk 2]
```diff
@@ -0,0 +1,399 @@
...
+    //				+ "schema=CCP and table=PLATFORMCONFIG");
+            testStmt.execute();
+        }
+        catch (SQLException ex)
+        {
+            errMsg = "Error setting VPD context for '" + dbOfficeId + "': " + ex;
+            log.severe(errMsg);
+            System.err.println(errMsg);
+            ex.printStackTrace(System.err);
+            throw new DbIoException(errMsg);
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsConnectionPool.java:382]: Whole lot of logging the same error message here.

File: src/main/java/decodes/cwms/CwmsConnectionPool.java [hunk 3]
```diff
@@ -0,0 +1,399 @@
...
+        }
+        return td;
+	}
+
+
+    public Connection getConnection() throws SQLException
+    {
+        connectionsRequested++;
+        Connection conn = pool.getConnection(info.getLoginInfo());
+        WrappedConnection wc = new WrappedConnection(conn,(c)->CwmsDbConnectionPool.close(c),Optional.of(this));
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsConnectionPool.java:158]: Shouldn't this call `returnConnection(c)` instead of passing to the `CwmsDbConnectionPool`?

File: src/main/java/decodes/cwms/CwmsConnectionPool.java [hunk 4]
```diff
@@ -0,0 +1,399 @@
...
+		String ret = null;
+		try
+		{
+			ArrayList<StringPair>officePrivileges = determinePrivilegedOfficeIds(conn);
+			// MJM 2018-12-05 now determine the highest privilege level that this user has in
+			// the specified office ID:
+			log.finest("Office Privileges for user '" + user + "'");
+			for(StringPair op : officePrivileges)
+			{
+				if (op == null)
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsConnectionPool.java:191]: logging at warning seems pretty high for these statements, especially without any context in the message.

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 5]
```diff
@@ -179,114 +193,113 @@ public void connectToDatabase(String sqlDbLocation)
...
+					}
+					catch(SQLException ex)
+					{
+						String msg = "Error in '" + q + "': " + ex
+							+ " -- will proceed anyway.";
+						Logger.instance().failure(msg + " " + ex);
+					}
+
+					cgl.setLoginSuccess(true);
+					Logger.instance().info(module +
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:255]: This logged message contains redundancies with previous "Connect to DECODES CWMS Database" message

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 6]
```diff
@@ -179,114 +193,113 @@ public void connectToDatabase(String sqlDbLocation)
...
-			String msg = "Error in '" + q + "': " + ex
-				+ " -- will proceed anyway.";
-			Logger.instance().failure(msg + " " + ex);
-		}
-		finally
-		{
-			try { st.close(); } catch(Exception ex) {}
-		}
+					String q = null;
+					try(Statement st = conn.createStatement();)
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:226]: recommend moving every statement into its own method to help debug connection management, as well as keeping the scope that is using the connection as minimal as possible.

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 7]
```diff
@@ -323,97 +336,34 @@ public IntervalDAI makeIntervalDAO()
...
-		}
-		catch (Exception ex)
-		{
-			String msg = module + ".getConnection() Cannot set VPD context username/officeId username='" 
-				+ conInfo.getLoginInfo().getUser()
-				+ "', officeId='" + dbOfficeId + "', officeCode=" + conInfo.getDbOfficeCode() + ", priv='"
-				+ conInfo.getDbOfficePrivilege() + "':" + ex;
-			Logger.instance().failure(msg);
-			try { CwmsDbConnectionPool.close(ret); } catch(Exception ex2) {}
+			Logger.instance().fatal("Unabled to get connection " + ex.getLocalizedMessage());
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:350]: Losing the `SQLException` stack trace info here

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 8]
```diff
@@ -323,97 +336,34 @@ public IntervalDAI makeIntervalDAO()
...
+		{
+			pool.returnConnection(con);
+		}
 		catch(SQLException ex)
 		{
-			Logger.instance().warning(module 
-				+ ".freeConnection() Error in CwmsDbConnectionPool.close: " + ex);
-			ex.printStackTrace(Logger.instance().getLogOutput() != null ? 
-				Logger.instance().getLogOutput() : System.err);
+			Logger.instance().warning("Unable to close returned connection: " + ex.getLocalizedMessage());
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:365]: Losing the SQLException stack trace here

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 9]
```diff
@@ -179,114 +193,113 @@ public void connectToDatabase(String sqlDbLocation)
...
 		try
 		{
-			st = conInfo.getConnection().createStatement();
-			
-			// Hard-code date & timestamp format for reads. Always use GMT.
-			q = "ALTER SESSION SET TIME_ZONE = 'GMT'";
-			Logger.instance().info(q);
-			st.execute(q);
+			pool = CwmsConnectionPool.getPoolFor(conInfo);
+			if( pool != null)
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:206]: This should never be null

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 10]
```diff
@@ -179,114 +193,113 @@ public void connectToDatabase(String sqlDbLocation)
...
-			Logger.instance().info(q);
-			st.execute(q);
+					// CWMS OPENDCS-16 for DB version >= 68, use old OracleSequenceKeyGenerator,
+					// which assumes a separate sequence for each table. Do not use CWMS_SEQ for anything.
+					int decodesDbVersion = getDecodesDatabaseVersion();
+					Logger.instance().info(module + " decodesDbVersion=" + decodesDbVersion);
+					keyGenerator = decodesDbVersion >= DecodesDatabaseVersion.DECODES_DB_68 ?
+							new OracleSequenceKeyGenerator() :
+							new CwmsSequenceKeyGenerator(decodesDbVersion);
+						TimeSeriesDb.readVersionInfo(this, conInfo.getConnection());
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:222]: `conInfo.getConnection()` is confusing here. I think this is the same `Connection` instance as the `conn` variable

File: src/main/java/opendcs/util/sql/WrappedConnection.java [hunk 11]
```diff
@@ -0,0 +1,394 @@
...
+    private ZonedDateTime start = ZonedDateTime.now();
+    private ZonedDateTime end = null;
+
+    
+
+    public WrappedConnection(Connection realConnection){
+        this(realConnection, (c) -> {},Optional.ofNullable(null));
+    }
+
+    public WrappedConnection(Connection realConnection, final ThrowingConsumer<Connection,SQLException> onClose, Optional<CwmsConnectionPool> pool )
```
Comment (adamkorynta) [inline src/main/java/opendcs/util/sql/WrappedConnection.java:63]: `Optional` pool is strange to me. How would the connection not be null, but the pool it came from not be null. Also this is an anti-pattern for the usage of Optional, it shouldn't be used as a parameter.

File: src/main/java/opendcs/util/sql/WrappedConnection.java [hunk 12]
```diff
@@ -0,0 +1,394 @@
...
+
+    @Override
+    public Statement createStatement() throws SQLException {
+        logPlainCreate();
+        return realConnection.createStatement();
+    }
+
+    private void logPlainCreate() {
+        log.debug2("Dev Msg: Plain create statement from:");
+        StackTraceElement stk[] = Thread.getAllStackTraces().get(Thread.currentThread());
```
Comment (adamkorynta) [inline src/main/java/opendcs/util/sql/WrappedConnection.java:160]: There should definitely be a `isLoggable()` check before snagging the stack traces. Also I would think that `Thread.currentThread().getStackTrace()` is cheaper than getting every thread's stack.

File: src/main/java/opendcs/util/sql/WrappedConnection.java [hunk 13]
```diff
@@ -0,0 +1,394 @@
...
+    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
+        realConnection.setTypeMap(map);
+    }
+
+    public CompositeData asCompositeData() throws OpenDataException
+    {
+        String[] itemNames = new String[1];
+        Object[] values = new Object[1];
+        itemNames[0] = "Lifetime";
+        values[0] = Duration.between(start, end == null ? ZonedDateTime.now() : end)
```
Comment (adamkorynta) [inline src/main/java/opendcs/util/sql/WrappedConnection.java:389]: seems like it would be good to log here if end is null and the duration between start and now has gone past some threshold.

File: src/main/java/decodes/cwms/CwmsConnectionPool.java (hunk 1 above)
Comment (MikeNeilson) [reply src/main/java/decodes/cwms/CwmsConnectionPool.java:312]: true, but it's also only called the once.

**Review by adamkorynta — COMMENTED** [review]
The change could use a good reformat to make them easier to read

File: src/main/java/decodes/cwms/CwmsConnectionPool.java (hunk 1 above)
Comment (adamkorynta) [reply src/main/java/decodes/cwms/CwmsConnectionPool.java:312]: Guess that's true, kinda hard to tell from the context of that single class

File: src/main/java/decodes/cwms/CwmsConnectionPool.java [hunk 14]
```diff
@@ -0,0 +1,399 @@
...
+                throw new BadConnectException("Unable to set office context.",ex);
+            }
+        }
+        return ret;
+    }
+
+
+    private CwmsConnectionPool(CwmsConnectionInfo info, Connection conn) throws BadConnectException,SQLException,DbIoException
+    {
+        this.info = info;
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsConnectionPool.java:76]: This constructor could use some love. I'd recommend removing all logic from here and moving to the factory method instead. Using one parameter to populate the other is adding a lot to the cognitive load here.

File: src/main/java/opendcs/util/sql/WrappedConnection.java (hunk 12 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/util/sql/WrappedConnection.java:160]: oh wow. I was doing currentThread in other places but totally missed that one.

File: src/main/java/opendcs/util/sql/WrappedConnection.java (hunk 11 above)
Comment (adamkorynta) [reply src/main/java/opendcs/util/sql/WrappedConnection.java:63]: Yeah that idea makes sense, but weird dependency-wise having the `opendcs` package depend on a `cwms` package. `private Optional<ConnectionPool> getConnectionPool() { Optional.ofNullable(this.pool);}` would work for this case.

Comment (MikeNeilson) [reply src/main/java/opendcs/util/sql/WrappedConnection.java:63]: Good point, actually I think it can just be dropped in favor of a simple boolean. The original intent had it actually using the object but now it's just don't do extra operations unless told.

File: src/main/java/decodes/cwms/CwmsConnectionPool.java [hunk 15]
```diff
@@ -0,0 +1,422 @@
...
+        try
+		{
+            String name = String.format("CwmsConnectionPool(%s/%s)",info.getLoginInfo().getUrl(),info.getLoginInfo().getUser());
+			ManagementFactory.getPlatformMBeanServer()
+							 .registerMBean(this, new ObjectName("org.opendcs:type=ConnectionPool,name=\""+name+"\""));
+		}
+		catch(JMException ex)
+		{
+			log.warning("Unable to register tracking bean " + ex.getLocalizedMessage());
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsConnectionPool.java:128]: Should include the exception itself as to not lose the stack trace

**Comment by MikeNeilson** [comment]
I do still have it running but thus far about 30 minutes with a CONNECT_TIME setting of 5 minute vs the 48 hours we have by requirement.

Plus in jconsole I see that the get/close is balanced.

Also running compproc and compdepends; both show  connection that stays open but those do tend to open and hold but each handles database failures fairly gracefully.

File: src/main/java/decodes/cwms/CwmsConnectionPool.java (hunk 3 above)
Comment (MikeNeilson) [reply src/main/java/decodes/cwms/CwmsConnectionPool.java]: No, it's operating on the actual connection.... granted that would've worked to and would clean up some logic I just implemented.

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java (hunk 10 above)
Comment (MikeNeilson) [reply src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:223]: it is, I was keeping as much original logic as possible before doing any larger tweaks. I think I can probably rip out the Connection variable from CwmsConnectionInfo now though.

File: src/main/java/opendcs/util/sql/WrappedConnection.java (hunk 11 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/util/sql/WrappedConnection.java]: cleaned up.

**Comment by MikeNeilson** [comment]
okay, compdepends failed, slight error in logic wrapping the connection (some how null is getting to the wrapped connection object) and for routsched a class seems to have gone missing. still, ran for several hours. so progress.

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java (hunk 6 above)
Comment (MikeNeilson) [reply src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:227]: agreed, but slightly beyond scope of this PR.

File: src/main/java/opendcs/util/sql/WrappedConnection.java (hunk 13 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/util/sql/WrappedConnection.java:396]: Yeah, but the bean info doesn't currently even show up. I'll fix up the JMX values in a later PR.

**Comment by MikeNeilson** [comment]
The loop in CompDepends has a balanced connections in/out. I suspect it's just failing at refreshCaches because I have a connect_time at 5 minutes. Then it appears to fail at the check for lock which in theory happens with a new connection so still a bit of investigation.

File: src/main/java/decodes/cwms/CwmsConnectionPool.java (hunk 3 above)
Comment (MikeNeilson) [reply src/main/java/decodes/cwms/CwmsConnectionPool.java]: thank you, that simplified things a lot.

**Comment by MikeNeilson** [comment]
> okay, compdepends failed, slight error in logic wrapping the connection (some how null is getting to the wrapped connection object) and for routsched a class seems to have gone missing. still, ran for several hours. so progress.

The logic to retrieve a connection and deal with a CONNECT_TIME error or Pool Full was wrong. Did the sane thing and made it a loop instead of trying to be clever with a goto (though it was fun to try.)

**Comment by MikeNeilson** [comment]
Okay, with the last to commits it's finally processing data. I will now let it run for the day and see how it survives.

**Comment by MikeNeilson** [comment]
It ran overnight! Success!

@adamkorynta A final sanity check is in order.

**Comment by MikeNeilson** [comment]
Though if I here nothing from people for a while I'm just going to merge it in.

File: ivysettings.xml [hunk 16]
```diff
@@ -23,6 +23,7 @@
                 <!-- https://github.com/lobobrowser/Cobra/releases/download/1.0.2/Cobra.jar -->
                 <artifact pattern="https://github.com/[organisation]/[module]/releases/download/[revision]/[artifact].[ext]"/>
             </url>
+            <ibiblio name="local" m2compatible="true" root="file:///home/mike/.m2/repository"/>
```
Comment (adamkorynta) [inline ivysettings.xml:26]: Local environment setting

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 17]
```diff
@@ -323,97 +337,34 @@ public IntervalDAI makeIntervalDAO()
 	public Connection getConnection()
 	{
 		// Called from DAOs and DbIo to get a new connection from the pool.
-		if (conInfo == null || conInfo.getLoginInfo() == null)
+		if (conInfo == null || conInfo.getLoginInfo() == null || pool == null)
 		{
 			Logger.instance().failure(module + ".getConnection -- loginInfo is null! DB not initialized?");
 			return null;
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:343]: Eventually I'd like to see this behavior changed to throwing a runtime exception. Trying to setup isolated tests becomes difficult when I'm getting null pointer exceptions on null connections.

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java [hunk 18]
```diff
@@ -323,97 +337,34 @@ public IntervalDAI makeIntervalDAO()
...
-			String msg = module + ".getConnection() Cannot set VPD context username/officeId username='" 
-				+ conInfo.getLoginInfo().getUser()
-				+ "', officeId='" + dbOfficeId + "', officeCode=" + conInfo.getDbOfficeCode() + ", priv='"
-				+ conInfo.getDbOfficePrivilege() + "':" + ex;
-			Logger.instance().failure(msg);
-			try { CwmsDbConnectionPool.close(ret); } catch(Exception ex2) {}
-			return null;
-			// TODO Should this method throw BadConnectException?
-//			throw new BadConnectException(msg);
+			Logger.instance().fatal("Unabled to get connection " + ex.getLocalizedMessage());
```
Comment (adamkorynta) [inline src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:351]: typo `Unable`, also do we really need a log line here when we are throwing the RuntimeException?

File: src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java (hunk 17 above)
Comment (MikeNeilson) [reply src/main/java/decodes/cwms/CwmsSqlDatabaseIO.java:343]: That's a good point, there's not really any recovery upstream from this anyways.

**Comment by adamkorynta** [comment]
Did we officially ditch JDK 7 support with the OpenDCS 7 release?

File: ivy.xml [hunk 19]
```diff
@@ -83,6 +83,7 @@
         <dependency org="org.junit.jupiter" name="junit-jupiter-engine" rev="5.8.1" conf="test->default"/>
         <dependency org="commons-io" name="commons-io" rev="2.11.0" conf="test->default"/>
         <dependency org="org.apache.derby" name="derby" rev="10.14.2.0" conf="test->default"/>
+        <dependency org="org.mockito" name="mockito-core" rev="4.8.0" conf="test->default"/>
```
[the remark this answers is not in the document]
Comment (MikeNeilson) [reply ivy.xml:86]: From an original attempt at setting this up. Should we leave it in those as a "yes, please go ahead and use this library" though?

**Comment by MikeNeilson** [comment]
Yes, we ditched JDK 7 support. why?

File: ivy.xml (hunk 19 above)
[the remark this answers is not in the document]
Comment (adamkorynta) [reply ivy.xml:86]: I wouldn't, no need to add in an extra dependency and declare a version if it isn't being used.

**Comment by adamkorynta** [comment]
I saw the lambdas, but didn't remember if that version cutoff was official.

File: ivy.xml (hunk 19 above)
[the remark this answers is not in the document]
Comment (MikeNeilson) [reply ivy.xml:86]: fair.

**Comment by MikeNeilson** [comment]
Ah, okay. Yeah. I believe that was why. Way too useful to ignore.... and no one should be using JDK/JRE 7 anyways.

**Review by adamkorynta — APPROVED** [review]
