### PR TITLE
Bugfix/routin scheduler again

### LINKED ISSUE #165: Routing scheduler with two routing specs immediately deadlocks in threaded logger
**Describe the bug**
Exactly as title.

**To Reproduce**
1. Creating instance of routingsheduler app
2. assign two or more routing specs
3. start the routing scheduler
4. wait a seconds
5. run jstack on the java pid to see the two routing spec threads stopped in the ThreadedLogger log method.

**Expected behavior**
Log writing properly synchronizes

**Screenshots**
```
"EDL-USGS" #39 prio=5 os_prio=64 tid=0x0000000101fda800 nid=0x4a waiting for monitor entry [0xffffffff5d7ee000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at ilex.util.ThreadLogger.log(ThreadLogger.java:141)
        - waiting to lock <0x00000005c03597b0> (a ilex.util.ThreadLogger)
        at ilex.util.Logger.debug3(Logger.java:303)
        at decodes.decoder.DecodedMessage.addSample(DecodedMessage.java:826)
        at decodes.decoder.FieldOperation.execute(FieldOperation.java:356)
        at decodes.decoder.DecodesOperationGroup.execute(DecodesOperationGroup.java:80)
        at decodes.db.FormatStatement.execute(FormatStatement.java:131)
        at decodes.db.DecodesScript.decodeMessage(DecodesScript.java:407)
        - locked <0x000000071b0839d8> (a decodes.db.DecodesScript)
        at decodes.routing.RoutingSpecThread.attemptDecode(RoutingSpecThread.java:707)
        at decodes.routing.RoutingSpecThread.run(RoutingSpecThread.java:554)

"CWMSv2-DCP-OTF" #38 prio=5 os_prio=64 tid=0x0000000102277800 nid=0x49 runnable [0xffffffff6ddeb000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        - locked <0x00000005c0f8e500> (a java.lang.Object)
        at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:174)
        at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555)
        at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:258)
        at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:190)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:132)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:105)
        at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91)
        at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:764)
        at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:429)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:407)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
        at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:765)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1362)
        - locked <0x00000005c0d32a50> (a oracle.jdbc.driver.T4CConnection)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:369)
        at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OracleStatement$$$Proxy.executeQuery(Unknown Source)
        at opendcs.dao.DaoBase.doQuery(DaoBase.java:198)
        at opendcs.dao.DacqEventDAO.<init>(DacqEventDAO.java:37)
        at decodes.sql.SqlDatabaseIO.makeDacqEventDAO(SqlDatabaseIO.java:2397)
        at decodes.routing.DacqEventLogger.writeDacqEvent(DacqEventLogger.java:64)
        at decodes.routing.DacqEventLogger.doLog(DacqEventLogger.java:56)
        at ilex.util.Logger.log(Logger.java:155)
        at ilex.util.ThreadLogger.log(ThreadLogger.java:143)
        - locked <0x00000005c03597b0> (a ilex.util.ThreadLogger)
        at ilex.util.Logger.warning(Logger.java:339)
        at decodes.comp.RatingComputation.apply(RatingComputation.java:184)
        at decodes.comp.ComputationProcessor.applyComputations(ComputationProcessor.java:97)
        - locked <0x00000005c0df4148> (a decodes.comp.ComputationProcessor)
        at decodes.routing.RoutingSpecThread.attemptDecode(RoutingSpecThread.java:732)
        at decodes.routing.RoutingSpecThread.run(RoutingSpecThread.java:554)

```

**ServerSide (please complete the following information):**
 - OS: Solaris 11/SPARC
 - Version: 7.0.4

**Additional context**
Looking at the code right now I'm honestly baffled as to way. There's no extra mutex locking than just the synchronized marker on the log call, and yet it's still deadlocking for us. I need to verify my test environment to see if I have that active and this is some weird Solaris/SPARC only java issue.

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Maybe Fixes #165. 
Fixes #159 .

Generally fixes issues with the connection pool that was likely due to a lack of synchronization.

## Solution

Cleaned up the logging and tracing in the CwmsConnectionPool and WrappedConnection objects.
Add synchronization to the CwmsConnectionPool. I noticed in VisualVM that I was getting incredibly odd results and that
was likely resulting in some of the failing connection we were still seeing.

Wrapped DacqEventDao usage in the new handlers
Wrapped PlatformStatusDAO usage into new handlers for some key queries.

## how you tested the change

Manually observing program flow through logs, nohup, and VisualVM.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

**Comment by MikeNeilson** [comment]
I am still testing, but wanted to get this in front of everyone. I'll do an internal release on monday to let a few people here test; several users have still been having issues.

**Comment by MikeNeilson** [comment]
Okay, so I still need to rebase this. However, I think I've gotten it to the point where the "RoutingScheduler" is fixed, however it's now exposing some other issues with SQL usage. I've fixed one in this PR. However if more are exposed I think it would to just merge this in and do each of those separate just to keep it simpler to review.

File: src/main/java/decodes/sql/SqlDatabaseIO.java [hunk 1]
```diff
@@ -2117,7 +2113,8 @@ public Connection getConnection()
 				Logger.instance().warning(
 					"SqlDatabaseIO.getConnection() Cannot get pooled connection: " + ex);
 			}
-		return _conn;
+		}
+		return new WrappedConnection(_conn, (c)->{/* do nothing */});
```
Comment (MikeNeilson) [inline src/main/java/decodes/sql/SqlDatabaseIO.java:2117]: This was required due to the changes in `PresentationGroupListIO` and the future changes.

**Comment by MikeNeilson** [comment]
I think I'm getting closer. While this PR is getting big, and there's clearly even more work for the database interaction as I think I stated previously if we can get this to work for at least a week with the CWMS and Postgresl databases we should call this PR good and merge it in, and then we can do smaller PRs for the remaining work given the structure of what to do is better defined.

File: src/main/java/decodes/routing/RoutingSpecThread.java [hunk 2]
```diff
@@ -175,6 +175,7 @@ public void setCurrentStatus(String currentStatus)
 	public RoutingSpecThread()
 	{
 		super();
+		setDaemon(true);
```
Comment (MikeNeilson) [inline src/main/java/decodes/routing/RoutingSpecThread.java:178]: Arguably debatable if this is correct here but I was having issues with the RoutingScheduler actually shutting down. Especially with newer JVMs

File: src/main/java/decodes/cwms/CwmsTimeSeriesDb.java [hunk 3]
```diff
@@ -809,19 +809,21 @@ public DbKey connect( String appName, Properties credentials )
...
-
-		CwmsGuiLogin cgl = CwmsGuiLogin.instance();
-		if (DecodesInterface.isGUI())
-		{
+		String username = null;
+		String password = null;
+		CwmsGuiLogin cgl = null;
+		if (credentials == null && DecodesInterface.isGUI())
+		{			
+			cgl = CwmsGuiLogin.instance();
```
Comment (ktarbet) [inline src/main/java/decodes/cwms/CwmsTimeSeriesDb.java:817]: comment from somebody new here:

Seeing the word 'Gui' in a database class feels odd.

Comment (MikeNeilson) [reply src/main/java/decodes/cwms/CwmsTimeSeriesDb.java:817]: Yeah, that particular code path is rather misplaced. I've recently merged in a more generic support for GUI Login and that will get fixed later. This change was to correct a bug that got introduced why I created the new `AuthSource` ServiceProviderInterface`.

File: src/main/java/decodes/datasource/LrgsDataSource.java [hunk 4]
```diff
@@ -94,9 +95,9 @@ public class LrgsDataSource extends DataSourceExec
       No-args constructor is necessary because this is instantiated from
       a Class object that was loaded dynamically.
     */
-    public LrgsDataSource()
+    public LrgsDataSource(DataSource ds, Database db)
```
Comment (ktarbet) [inline src/main/java/decodes/datasource/LrgsDataSource.java:98]: The comment above needs to be adjusted -- constructor now has args.

File: src/main/java/decodes/datasource/InputDirectory.java [hunk 5]
```diff
@@ -47,9 +48,9 @@ public class InputDirectory
 	extends DataSourceExec
 {
 	/** default constructor */
-	public InputDirectory()
+	public InputDirectory(DataSource ds, Database db)
```
Comment (ktarbet) [inline src/main/java/decodes/datasource/InputDirectory.java:51]: With args, I don't think this is considered a default constructor as comment above calls it.

Comment (ktarbet) [reply src/main/java/decodes/datasource/InputDirectory.java:51]: There are several other Class that how have args, making the comments about default constructors confusing.

Comment (MikeNeilson) [reply src/main/java/decodes/datasource/InputDirectory.java:51]: Yep. I need to clean that up. I can't remember exactly what I was tracking down but it had to do with the singleton access to the `Database` class and and getting the `DataSource` assigned. but some of those could actually use a default constructor and I didn't even think about the JavaDocs.

File: src/main/java/decodes/routing/DacqEventLogger.java [hunk 6]
```diff
@@ -58,6 +58,7 @@ public void doLog(int priority, String text)
 	
 	public void writeDacqEvent(DacqEvent evt)
 	{
+		/* TODO: Too many Fkey errors, will review later
```
Comment (ktarbet) [inline src/main/java/decodes/routing/DacqEventLogger.java:61]: - [ ] Too many Fkey errors, will review later

File: src/main/java/decodes/db/Database.java [hunk 7]
```diff
@@ -139,8 +139,11 @@ public Database(int type, String location)
 	/**
 	 * Retrieves the 'current' database.
 	 * The 'current' database is set by a previous call to setDb().
+	 * @returns a global instance of the database
+	 * @deprecated since 7.0.9 existing code can use this, but anything totally new that requires the decodes database
+	 * *MUST* take the Database in its constructor. If upgrading/updating things at least consider trying to move
+	 * to constructor injections; even if it means just moving this call up a level.
 	 */
```
Comment (ktarbet) [inline src/main/java/decodes/db/Database.java:146]: consider adding @deprecated annotation.

**Review by ktarbet — COMMENTED** [review]
The pattern below is used several times.   Is there a new object, to be discovered, that could hold both DataSource and Database (to be passed around),  or could DataSource hold the DataBase?

```java
public MyFriendlySource(DataSource ds, Database db)
	{
		super(ds,db);
    // coding, coding
       }

**Comment by MikeNeilson** [comment]
> The pattern below is used several times. Is there a new object, to be discovered, that could hold both DataSource and Database (to be passed around), or could DataSource hold the DataBase?
> 
> ```java
> public MyFriendlySource(DataSource ds, Database db)
> 	{
> 		super(ds,db);
>     // coding, coding
>        }
> ```

this particular datasource is a reference to the source to hydrologic data, it's not a configuration java.sql.DataSource like the Database could be/use. So it doesn't make sense to combine them.

File: src/main/java/decodes/db/Database.java (hunk 7 above)
Comment (MikeNeilson) [reply src/main/java/decodes/db/Database.java:146]: Thanks, it showed cross in my IDE so I probably just thought it was there.

**Comment by MikeNeilson** [comment]
@opendcs/opendcs-core-devs @ktarbet 
The last few failures have been mostly out-of-memory (specially a "could not reclaim enough memory" error), which I think have been valid in that I didn't allocation sufficient memory for the number of RoutingSpecs that were continuously running.

The last apparently possible other issue was cleaning up the PropertiesDAO sql. If the next failure is something similar I'm going to call this initial work done. I think I still need to fix some issues with the Postgres implementation after this is merged in (kept having rather random GUI failures and lockups) but this PR is already huge so I think it's worth risking a possibly broken system while we sort through things.

I am making progress on getting more tests in place, the integration system should be easier to expand now, need to get a computation test in next and clean up the actual baseline setup and input/output data but the reasonable hooks are in place at least.

**Comment by MikeNeilson** [comment]
Okay, it almost ran for a week, and then I did a small live hotfix on the database under test and it exited correctly for that kind of condition. 

I'm going to let it run again over the weekend but otherwise consider this PR "good". I will go through it for silly things and there may still be issues with the DACQ event logger.

Also I noticed in my homelab opendcs usage (where this PR is merged in) that the GUIs would fail fairly quickly, and it appeared to be database issues. I'm going to go through those but will likely be a different PR just to keep this one smaller.

**Comment by MikeNeilson** [comment]
Okay, it ran from Tuesday morning to Monday Morning. There appears to still be an odd failure mode were the scheduler runs but the routingspecs don't but this PR is already too big.

So I think my finish this PR conditions are met. There's still some follow up, I did already figure out what was wrong with the Postgres implementation (just needed to make sure all getConnection calls return a WrappedConnection with a do-nothing on close) but those changes will be easier to review in smaller PRs.

File: src/main/java/opendcs/dao/DacqEventDAO.java [hunk 8]
```diff
@@ -59,43 +59,42 @@ public void writeEvent(DacqEvent evt) throws DbIoException
 		String txt = evt.getEventText();
 		if (txt.length() >= 256)
 			txt = txt.substring(0,255);
+
+		StringBuilder q = new StringBuilder();
+		q.append("INSERT INTO " + tableName + "(" + columns + ") VALUES(?,?,?,?,?,?,?,?");
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/DacqEventDAO.java:64]: At first glance, tableName looks like a input string (actually it is final static string).  Perhaps this could be renamed to DACQ_EVENT_TABLE_NAME, in the future.

File: src/main/java/opendcs/dao/PlatformStatusDAO.java [hunk 9]
```diff
@@ -52,13 +52,11 @@ public synchronized PlatformStatus readPlatformStatus(DbKey platformId)
 			return null;
 		
 		String q = "select " + ps_attrs + " from platform_status "
-			+ "where platform_id = " + platformId;
+			+ "where platform_id = ?";// + platformId;
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/PlatformStatusDAO.java:55]: consider removing commented code.

File: src/main/java/opendcs/dao/DbObjectCache.java [hunk 10]
```diff
@@ -84,14 +86,28 @@ public void put(DBT dbObj)
...
-			nameIsCaseSensitive ? ow.obj.getUniqueName() : ow.obj.getUniqueName().toUpperCase());
-		keyObjMap.remove(key);
+		try
+		{
+			nameObjMap.remove(
+				nameIsCaseSensitive ? ow.obj.getUniqueName() : ow.obj.getUniqueName().toUpperCase());
+		}
+		catch(NoSuchElementException ex)
+		{
+			// another thread already removed it.
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/DbObjectCache.java:101]: with the synchronized keyword, won't that also prevent another thread from removing?

File: src/main/java/opendcs/dao/PropertiesSqlDao.java [hunk 11]
```diff
@@ -36,36 +37,38 @@
...
 			throws DbIoException
 	{
-		String q = "select * from " + tableName + " where " + idColumn + " = " + parentKey;
-		
-		ResultSet rs = doQuery(q);
+		Objects.requireNonNull(props, "A valid properties object must be passed into this function.");
+		Objects.requireNonNull(tableName, "A valid table name is required.");
+		Objects.requireNonNull(parentKey, "A valid Database Identifier is required.");
+		Objects.requireNonNull(idColumn, "The id column must be valid.");
+		String q = "select * from " + tableName + " where " + idColumn + " = ?";
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/PropertiesSqlDao.java:61]: Any chance the tableName or idColumn could be evil input?  Code is trusting jdbc PreparedStatement take care of that; proabably OK in this context.  Consider simple check for (letters and underscore only names).  i.e. validTableName(), validColumnName() could augument requireNonNull .   Could be applied to other code in this file PropertiesSqlDao.

File: src/main/java/opendcs/dao/DbObjectCache.java (hunk 10 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/dao/DbObjectCache.java:101]: Possible. But will require much more analysis to verify.

File: src/main/java/opendcs/dao/PropertiesSqlDao.java (hunk 11 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/dao/PropertiesSqlDao.java:61]: Yes, technically, but one would have to get the evil change through the pull request process.

This is a common, if not great, idom in jdbc when conditions require varying names or columns.
