### PR TITLE
Bugfix/745 routing spec updates

### LINKED ISSUE #745: Issue saving/updating routing spec
**Describe the bug**
DbEdit hangs, and then reports failure, while updating a routing spec.

**To Reproduce**
1. Open Decodes Database Editor
2. Go to routings tab
3. copy a routing
4. attempt to update
5. see errors about parent key missing

**Expected behavior**
Updates save correctly.

**Screenshots**

**Desktop/ServerSide (please complete the following information):**
 - OS: Ubuntu
 - Version 7.0.13, latest commit

**Additional context**
After a minor tweak to the code the hang happens.

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Fixes #745. 

Describe the problem you are trying to solve.

## Solution

1. Moved all operations within the appropriate try-catch block
2. Modified function calls in RoutingSpecListIO so ensure the same connection/transaction was used for all operations
3. Added an addOrReplace to TableModel to prevent needless deletion from the database.
4. Migrated propertiesDAO to use bind variables
5. Migrated more of RoutingSpecListIO operations to use bind variables (new handlers to properly wrap connections are at least used.)
6. Changed GUI behavior on commit. A TraceDialog will open, if successful will close automatically, if not it will remain open with the contents of the error.
7. Changed GUI behavior on copy. No longer immediately saves the copy.
8. Changed GUI behavior on save. Database operations now off GUI thread.

## how you tested the change

Manually
1. copied routing spec, saved, closed/repoen dbedit, verified it remained.
2. opened routing spec, modified, saved, closed/reopen dbedit, verified it remained and had changes.
3. opened routing spec, modified with bad data (properties too long), saved, saw errors, closed/repopen dbeidt, verified it remained with original data.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: src/main/java/decodes/dbeditor/routing/RSListTableModel.java [hunk 1]
```diff
@@ -112,6 +112,16 @@ public void addObject(RoutingSpec ob)
         fireTableDataChanged();
     }
 
+    public void addOrReplace(RoutingSpec ob)
+    {
+        RoutingSpec found = theList.find(ob.getName());
+        if (found != null)
+        {
+            theList.remove(found);
```
Comment (ktarbet) [inline src/main/java/decodes/dbeditor/routing/RSListTableModel.java:120]: does the database version also need to be deleted here? (call deleteObject(RoutingSpec ob)

File: src/main/java/opendcs/dao/PropertiesSqlDao.java [hunk 2]
```diff
@@ -182,77 +194,83 @@ public void deleteProperties(String tableName, String idColumn,
...
                         if (value == null)
+                        {
                             value = "";
+                        }
 
                         chp.setProperty(name, value);
-                        n++;
-                        continue nextProp;
+                        n.getAndIncrement();
+                        return;
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/PropertiesSqlDao.java:264]: This return 'feels' like we will only get one item?

**Review by ktarbet — COMMENTED** [review]
the build was failing, I've added some comments.

File: src/main/java/decodes/dbeditor/routing/RSListTableModel.java (hunk 1 above)
Comment (MikeNeilson) [reply src/main/java/decodes/dbeditor/routing/RSListTableModel.java:120]: This is specifically *not* calling the database delete, as "add" doesn't call the database write, and thus the Spec will magically disappear from the database.

There's a lot of things to fix, or just make a firm decision about, in the table models.

File: src/main/java/opendcs/dao/PropertiesSqlDao.java (hunk 2 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/dao/PropertiesSqlDao.java:264]: no, that return move to the next ResultSet so it could increment from that. Honestly that whole block confuses me in design, had a jump to label originally.

**Review by DanielTOsborne — APPROVED** [review]
Looks good to me. I tested this branch locally and only ran into an issue with the updated item changing order in the list, but commit cc5d6be4e95a511708be26dcfca2fc2dbd25ed8c fixes that.
