### PR TITLE
Bugfix/480 connection usage

### LINKED ISSUE #480: CCP Process Failed - Unable to get connection from pool
**Describe the bug**
A process failed in OpenDCS 7.0.11 from not being able to get a connection from pool (see log snippet below). I've never had a process fail out of the blue before and these comps/process has been running without issue for months/years. It was on the weekend so it failed completely on its own. I restarted the process, and it seems to be running along fine again.

```DBG2    02/10/24 20:28:11 Dev Msg: Plain create statement from:
DBG1    02/10/24 20:28:11 CwmsTimeSeriesDAO After fill, cache has 11450 TSIDs.
DBG1    02/10/24 20:28:12 CwmsTimeSeriesDAO reloadTsIdCache()
FAILURE 02/10/24 20:28:12 CwmsTimeSeriesDb Unable to get connection from pool: ORA-20998: ERROR: Unable to set a default SESSION_OFFICE_ID. The user:  either has no assigned CWMS database privileges or has privileges to more than one office. Please see your CWMS Application Admin.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_ENV", line 49
ORA-28112: failed to execute policy function
ORA-06512: at "CWMS_20.CWMS_UTIL", line 626
ORA-06512: at "CWMS_20.CWMS_ENV", line 45
ORA-06512: at line 1

WARNING 02/10/24 20:28:12 GateCalcs_09-10 Unexpected exception while Getting new data: java.lang.RuntimeException: Error retrieving connection.
DBG1    02/10/24 20:28:12 runApp() exiting.
INFO    02/10/24 20:28:12 Closing database connection.
INFO    02/10/24 20:28:12 Shutting down Decodes Connection.
INFO    02/10/24 20:28:12 Closing  database connection.
INFO    02/10/24 20:28:12 GateCalcs_09-10 exiting.```

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Fixes #480, maybe. 

Describe the problem you are trying to solve.

## Solution

Verify connections are being used correctly.

## how you tested the change

Need to write new or port tests.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: src/main/java/decodes/cwms/rating/CwmsRatingDao.java [hunk 1]
```diff
@@ -77,339 +39,337 @@
...
+     * @param xml
+     * @throws RatingException
+     */
+    public void importXmlToDatabase(String xml)
+        throws RatingException
+    {
+        log.trace("importXmlToDatabase: {}");
+        RatingSet newSet = RatingSet.fromXml(xml);
+        String specId = newSet.getRatingSpec().getRatingSpecId();
+        log.trace("importXmlToDatabase fromXml success, specId='{}'", specId + "'");
```
Comment (ktarbet) [inline src/main/java/decodes/cwms/rating/CwmsRatingDao.java:256]:
```suggestion
        log.trace("importXmlToDatabase fromXml success, specId='{}'", specId );
```

File: src/main/java/decodes/dbeditor/TraceLogger.java [hunk 2]
```diff
@@ -68,6 +68,15 @@ public void close()
...
 	{
-		queue.add(text + "\n");
+		try
+		{
+			queue.put(text + "\n");
+		}
+		catch (InterruptedException ex)
+		{
+			// NOTE: use of STDERR is intentional here. This is an error with logging itself.
+			System.err.println("Unable to Write message to log queue.");
```
Comment (ktarbet) [inline src/main/java/decodes/dbeditor/TraceLogger.java:78]:
```suggestion
			System.err.println("Unable to Write message to log queue.");
			System.err.println("Message: '"+text+"'");
```
```suggestion
			System.err.println("Unable to Write message to log queue.");
```

File: src/main/java/opendcs/dao/ComputationDAO.java [hunk 3]
```diff
@@ -171,17 +176,17 @@ private void fillCache()
 
 		try
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/ComputationDAO.java:177]: fillCache() is called from listCompsForGUI() only if the compCache is empty.  Which seems OK if this is for a UI.  However, if there are other paths to fillCache() clearing the cache may be necessary., perhaps a first step in fillCache() should be to clear the cache?

File: src/main/java/opendcs/dao/ComputationDAO.java [hunk 4]
```diff
@@ -875,53 +886,55 @@ public void writeComputation( DbComputation comp )
 		throws DbIoException
 	{
 		Logger.instance().debug2("writeComputation name=" + comp.getName());
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/ComputationDAO.java:888]:
```suggestion
		log.trace("writeComputation name= {}", comp.getName());
```

Consider coming back with a separate PR to finish out the logging migration to slf4j .  I'm willing to help on that.

Comment (MikeNeilson) [reply src/main/java/opendcs/dao/ComputationDAO.java:888]: will do, was mostly updating the sections I was using to identify issues.

File: src/main/java/opendcs/dao/ComputationDAO.java (hunk 3 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/dao/ComputationDAO.java:177]: hmm, it's private so I don't think it will but I'll check later on the execution paths. Though even with just for the GUI it should clear the cache, entirely plausible things have been deleted in the meantime.

Comment (MikeNeilson) [reply src/main/java/opendcs/dao/ComputationDAO.java:177]: I've put it in for good measure, but it doesn't actually appear needed. The compedit GUI uses the function below this one. And the other usages just call this and it checks if it's ever been called. We'll definitely need to look into this cache later.

File: src/main/java/opendcs/dao/ComputationDAO.java
Comment (ktarbet) [inline src/main/java/opendcs/dao/ComputationDAO.java:1]: Future: The process of writing Computations could use some space, such as it's own class.

File: src/main/java/opendcs/dao/TsGroupDAO.java [hunk 5]
```diff
@@ -122,14 +123,12 @@ public TsGroup getTsGroupById(DbKey groupId, boolean forceDbRead)
 //else debug2("READING FROM DATABASE group id " + groupId);
 		
 		String q = "SELECT " + GroupAttributes + " FROM tsdb_group "
-			+ "WHERE group_id = " + groupId;
+			+ "WHERE group_id = ?";
 		try
 		{
-			ResultSet rs = doQuery(q);
-			if (rs != null && rs.next())
+			ret = getSingleResultOr(q, rs -> rs2group(rs), (TsGroup)null, groupId);
```
Comment (ktarbet) [inline src/main/java/opendcs/dao/TsGroupDAO.java:129]: does the parameter argument(s), in this case groupId, need to be a primitive type?   groupId is a DbKey .

File: src/main/java/org/opendcs/utils/logging/LogFilter.java
Comment (ktarbet) [inline src/main/java/org/opendcs/utils/logging/LogFilter.java:1]: A comment would be helpful to know if LogFilter is excluding specific loggerNames, or allowing specific LoggerNames.

File: src/main/java/opendcs/dao/TsGroupDAO.java (hunk 5 above)
Comment (MikeNeilson) [reply src/main/java/opendcs/dao/TsGroupDAO.java:129]: No, the parameters array is of type Object, the "bind" function in DaoBase takes care of appropriate SQL type mapping.

**Review by ktarbet — COMMENTED** [review]
Here is  PR into this PR: https://github.com/opendcs/opendcs/pull/594

**Review by ktarbet — APPROVED** [review]
