### PR TITLE
Use combined trust in webabstract data source.

### LINKED ISSUE #1203: WebSource Certificate validation
**Describe the bug**
Two usace users have reported certificate validation errors in our primary environment

**To Reproduce**
1. Difficult, only appears during automated runs on the given hosts
2. PXIX error, which generally means certificate chain validation failures.

**Expected behavior**
No failure, or a reasonable message.

**Screenshots**

**Desktop/ServerSide (please complete the following information):**
 - OS: Solaris 11
 - Version All.

**Additional context**
It is also possible for the HTTPS target to have an invalid certificate setup that causes the error.

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Fixes #1203. 

## Solution

- Created Default trust existing/log untrusted certficate test
- Move LrgsConnection::socketFactory to WebUtility::socketFactory
- Updated WebUtility methods to include combined trust if HTTPSUrlConnection
- Non GUI usages use the above trust/existing log untrusted
- GUI usage use the X509CertificateVerifierDialog to present the decision to the user.

## how you tested the change

Create Unit tests.

Adds mock-server as a test dependency. This library was previously used in the maven-uploader-plugin and greatly simplifies testing HTTP and HTTPS calls.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: java/opendcs/src/main/java/org/opendcs/utils/WebUtility.java [hunk 1]
```diff
@@ -1,22 +1,142 @@
...
+     *                 should be.
+     * @return
+     */
+    public static SSLSocketFactory socketFactory(Predicate<TrustManagerParameters> certTest)
+    {
+        SSLFactory sslFactory = SSLFactory.builder()
+                                          .withDefaultTrustMaterial()
+                                          .withSystemTrustMaterial()
+                                          .withInflatableTrustMaterial(
+                                            Paths.get(EnvExpander.expand("$DCSTOOL_USERDIR/local_trust.p12")),
```
Comment (ktarbet) [inline java/opendcs/src/main/java/org/opendcs/utils/WebUtility.java:135]: Should this filename be configurable.  I don't know if users need to modify.

**Review by ktarbet — APPROVED** [review]
