### PR TITLE
Bugfix/1256 logging fixes

### LINKED ISSUE #1256: CompProc partial operations and failed loging.
**Describe the bug**
CompProc appears to be somewhat working (if very slow) but no log entries until restart after a point.

**To Reproduce**
1. run comppproc with a lot of data
2. wait
3. see various missing data, some saved, no log entries after a point.

**Expected behavior**
Continued logging and data processing.

**Screenshots**

**Desktop/ServerSide (please complete the following information):**
 - Version [main, 7.0.15]

**Additional context**

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Possibly Fixes #1256. 

Describe the problem you are trying to solve.

## Solution

Original system was logging one entry at a time using `Queue::poll`
Before changes I printed the entries in queue vs queue size and artificially shrunk the queue. There did appear to be the possibility of things hanging on adding new log entries to the queue which could have gotten things stuck. Additionally it may have been that the log was rotated but never picked up correctly hence the lack of updated log messages.

This change makes the log rotation a tighter part of the writing loop and should handle that situation better.

## how you tested the change

Unit test was updated to verify behavior of rotation.
Manually tests with compproc instance to see if responses were reasonable.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: java/opendcs/src/main/java/ilex/util/FileLogger.java [hunk 1]
```diff
@@ -26,6 +31,17 @@
...
 public class FileLogger extends Logger
 {
+	/**
+	 * Message Queue capacity.
+	 *
+	 * This number is currently rather arbitrary and may need adjustment in the future.
+	 */
+	private static final int MESSAGE_CAPACITY = 5000;
+	/**
+	 * Numbered of queued messages to log in a single batch
```
Comment (ktarbet) [inline java/opendcs/src/main/java/ilex/util/FileLogger.java:41]:
```suggestion
	 * Number of queued messages to log in a single batch
```

**Review by ktarbet — APPROVED** [review]
