### PR TITLE
Fixes #449 -  Python Alogorithm Scripts - Column sorting issue

### LINKED ISSUE #449: Python Alogorithm Scripts - Column sorting issue
**Describe the bug**
Sorting confuses the 'Select CP Functions Function' dialog
**To Reproduce**
using windows Client (building from master 7.0.12), connected to a CWMS Database

1. open Computations
2. Open a python algorithm
3. Click 'CCP Built-in' button
4. Click Name column to sort.
5.Click the 'screening' under Name.

Before Sorting Description is correct as shown for screening for example:
image

After Sorting
image

### PR DESCRIPTION
**Pull request by ktarbet**
Fixes #449 

## Solution

Using basic JTable features to get the job done, while removing code.

## how you tested the change

Startup OpenDCS , Click Alogrithms, pick a PythonAlgorithm,  Click the Python Button,  Click Python Built-in.
Select functions and insert, try sorting and verify descriptions stay in sync.

### CODE REVIEW

File: src/main/java/decodes/tsdb/compedit/PyFuncSelectDialog.java [hunk 1]
```diff
@@ -77,31 +50,24 @@ public PyFuncSelectDialog(JFrame theFrame, PyFuncList funcList)
...
-			}
-		});
+		cancelButton.addActionListener(e -> cancelPressed());
 		buttonPanel.add(cancelButton);
 
-		// Set up the table
-		if (model == null)
-			model = new FuncListTableModel(funcList);
-		tab = new SortingListTable(model, new int[] {30,70});
+		model = new DefaultTableModel(new String[]{"Name", "Signature","Function"},0);
```
Comment (MikeNeilson) [inline src/main/java/decodes/tsdb/compedit/PyFuncSelectDialog.java:61]: Since we're making this change anyways we should put these labels in the resource bundle: https://github.com/opendcs/opendcs/blob/master/src/main/resources/decodes/resources/compedit_en_US.properties

For future internationalization.

**Review by MikeNeilson — CHANGES_REQUESTED** [review]
This looks good. The labels from a resource can happen later, but if it seems easier to fix now we should just do it.

**Comment by MikeNeilson** [comment]
I'm going to argue these table sorting fixes are an "already identified" issues and can and should go in during the release candidate window.

File: src/main/java/decodes/tsdb/compedit/PyFuncSelectDialog.java (hunk 1 above)
Comment (ktarbet) [reply src/main/java/decodes/tsdb/compedit/PyFuncSelectDialog.java]: done in latest commit

**Review by MikeNeilson — APPROVED** [review]
