### PR TITLE
#1651: Swapped ConfigSensor min/max presentation in Web UI

### LINKED ISSUE #1651: Web UI Config - Sensor Min/Max ranges swapped
**Describe the bug**
The Config Sensor Valid Range Min/Max values appear to be swapped in the Web UI.  For example, the Config MRR-AKIA Min = 36 and Max = 0.

**To Reproduce**
1. Open Web UI Config that contains sensor range information (MRR-AKIA for NWK profile on HEC test server)
2. Click on the first Stage sensor (sensor 2)
3. See Valid Range

**Expected behavior**
Expect Valid Range to match what is in the client.

**Screenshots**
Web UI:
Image

7.0.15 Client
Image

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 11 Microsoft Edge
 - Client Version 7.0.15

### PR DESCRIPTION
**Pull request by zack-rma**
## Problem Description
Fixes #1651. 

## Solution
Swapped indexes for ConfigSensor minimum and maximum value fields in web UI. Added check for null min/max values to prevent empty values being represented as max float value in UI.

## how you tested the change

Tested locally in web UI.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: java/opendcs/src/main/java/decodes/sql/ConfigListIO.java [hunk 1]
```diff
@@ -266,8 +266,8 @@ private void readConfigSensors(DbKey platformConfigId, PlatformConfig pc)
                             equipId, _pcList.getDatabase());
                 }
 
-                if (hasAbsMin) cs.absoluteMin = absMin;
-                if (hasAbsMax) cs.absoluteMax = absMax;
+				cs.absoluteMin = hasAbsMin ? absMin : Double.MIN_VALUE;
```
Comment (adamkorynta) [inline java/opendcs/src/main/java/decodes/sql/ConfigListIO.java]: I don't see an absolute compare against `Const.undefinedDouble`, this would come back as a valid value
