### PR TITLE
Timed Computations and HDBSiteDAO Fixes

### LINKED ISSUE #573: Timed Computations ignore the "enabled" flag
**Describe the bug**
When a computation is scheduled via the timedCompInterval and timedCompOffset properties, it executes regardless if the "enabled" flag is false.

Indeed, nowhere in ComputationApp.java does it check the timed computations for their enabled status.

**Expected behavior**
Computation App shouldn't execute timed computations if they're disabled. This flag isn't checked for triggered computations because the triggering mechanisms and the compdepends process obey the enabled flag.

**Additional context**
Observed in HDB instance.

### LINKED ISSUE #611: HDB Computation Processor Cache Broken
**Describe the bug**
Looks like the differences in how HDB handles the site table has been completely removed from the computation cache fill code path? The buildSiteQuery function override used to handle the differences, and that was removed. This has completely broken HDB computation processor usage.

```
DBG1    06/14/24 15:39:01 259 cp_comp_ts_parm recs read.
DBG3    06/14/24 15:39:01 HDB Query1 'select SITE_DATATYPE_ID, SITE_ID, DATATYPE_ID from HDB_SITE_DATATYPE'
DBG3    06/14/24 15:39:01 HDB Query1 'select SITE_ID, DATATYPE_ID from HDB_SITE_DATATYPE where SITE_DATATYPE_ID = 32169'
FAILURE 06/14/24 15:39:01 HdbSiteDAO Error in readSite(a.site_id=5040): java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

WARNING 06/14/24 15:39:01 Exception filling computation hash.
WARNING 06/14/24 15:39:01 decodes.tsdb.DbIoException: Error in readSite(a.site_id=5040): java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

        at opendcs.dao.SiteDAO.readSite(SiteDAO.java:402)
        at opendcs.dao.SiteDAO.getSiteById(SiteDAO.java:149)
        at decodes.tsdb.TimeSeriesDb.getSiteById(TimeSeriesDb.java:1448)
        at decodes.hdb.HdbTimeSeriesDb.expandSDI(HdbTimeSeriesDb.java:380)
        at opendcs.dao.ComputationDAO.fillCache(ComputationDAO.java:245)
        at opendcs.dao.ComputationDAO.listCompsForGUI(ComputationDAO.java:564)
        at decodes.tsdb.ComputationApp.checkMissingChecks(ComputationApp.java:1155)
        at decodes.tsdb.ComputationApp.runAppInit(ComputationApp.java:622)
        at decodes.tsdb.ComputationApp.runApp(ComputationApp.java:322)
        at decodes.tsdb.TsdbAppTemplate.execute(TsdbAppTemplate.java:180)
        at decodes.tsdb.ComputationApp.main(ComputationApp.java:668)
```

**Additional context**
https://github.com/opendcs/opendcs/blob/master/src/main/java/opendcs/dao/SiteDAO.java#L387 doesn't work on HDB. 

I'm worried how many other subtle breakages have occurred in these refactors.

### PR DESCRIPTION
**Pull request by agilmore2**
## Problem Description

Fixes #611 
Fixes #573 

## Solution

Query right site tables in HDB
Filter by enabled flag in timed computations query

## how you tested the change

Manual testing of timed computation 

## Where the following done:
- [X] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

**Comment by agilmore2** [comment]
Commented useless cache fill from getNewData call. Mirrors changes to CMWS version.

File: src/main/java/decodes/hdb/HdbTimeSeriesDAO.java [hunk 1]
```diff
@@ -1189,12 +1189,13 @@ public DataCollection getNewData(DbKey applicationId)
 		throws DbIoException
 	{
 		// Reload the TSID cache every hour.
+		/* // Since DAO is recreated every compApp loop, avoid reloading cache every time
```
Comment (MikeNeilson) [inline src/main/java/decodes/hdb/HdbTimeSeriesDAO.java:1192]: I usually recommend just deleting blocks like this. it's in version control.

File: src/main/java/decodes/tsdb/ComputationApp.java [hunk 2]
```diff
@@ -785,13 +785,15 @@ private void checkTimedCompList(long now, Calendar timedCompCal)
 			+ "(select cmp.computation_id, cmp.date_time_loaded "
 				+ "from cp_comp_property cprop, cp_computation cmp "
 				+ "where cprop.computation_id = cmp.computation_id "
-				+ "and lower(prop_name) = 'timedcompinterval'"
+				+ "and lower(prop_name) = 'timedcompinterval' "
+				+ "and cmp.enabled = 'Y' "
 				+ "and cmp.loading_application_id = " + getAppId() + ") q1"
```
Comment (MikeNeilson) [inline src/main/java/decodes/tsdb/ComputationApp.java:790]: This could use the new handler/bind var treatment but I'll take care of that later. I vague recall some issues with "truth" values between the various implementations.

**Review by MikeNeilson — APPROVED** [review]

File: src/main/java/decodes/tsdb/ComputationApp.java (hunk 2 above)
Comment (agilmore2) [reply src/main/java/decodes/tsdb/ComputationApp.java:790]: the text2bool helper looks to accept true, yes, on for reading booleans? These are a one character field in HDB, Y or N by convention. Are the other implementations different here?

Comment (MikeNeilson) [reply src/main/java/decodes/tsdb/ComputationApp.java:790]: I need to review. CWMS itself uses 'T' and 'F' but I think all the OpenDCS usages use 'Y' and 'N', I would like to make the whole thing more robust in general. Just not really sure how to do it yet.
